/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "c2s.pb-c.h"
void   protos__registration__init
                     (Protos__Registration         *message)
{
  static Protos__Registration init_value = PROTOS__REGISTRATION__INIT;
  *message = init_value;
}
size_t protos__registration__get_packed_size
                     (const Protos__Registration *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__registration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__registration__pack
                     (const Protos__Registration *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__registration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__registration__pack_to_buffer
                     (const Protos__Registration *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__registration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__Registration *
       protos__registration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__Registration *)
     protobuf_c_message_unpack (&protos__registration__descriptor,
                                allocator, len, data);
}
void   protos__registration__free_unpacked
                     (Protos__Registration *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__registration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__commitment_req__init
                     (Protos__CommitmentReq         *message)
{
  static Protos__CommitmentReq init_value = PROTOS__COMMITMENT_REQ__INIT;
  *message = init_value;
}
size_t protos__commitment_req__get_packed_size
                     (const Protos__CommitmentReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__commitment_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__commitment_req__pack
                     (const Protos__CommitmentReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__commitment_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__commitment_req__pack_to_buffer
                     (const Protos__CommitmentReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__commitment_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__CommitmentReq *
       protos__commitment_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__CommitmentReq *)
     protobuf_c_message_unpack (&protos__commitment_req__descriptor,
                                allocator, len, data);
}
void   protos__commitment_req__free_unpacked
                     (Protos__CommitmentReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__commitment_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__key_lookup__init
                     (Protos__KeyLookup         *message)
{
  static Protos__KeyLookup init_value = PROTOS__KEY_LOOKUP__INIT;
  *message = init_value;
}
size_t protos__key_lookup__get_packed_size
                     (const Protos__KeyLookup *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__key_lookup__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__key_lookup__pack
                     (const Protos__KeyLookup *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__key_lookup__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__key_lookup__pack_to_buffer
                     (const Protos__KeyLookup *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__key_lookup__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__KeyLookup *
       protos__key_lookup__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__KeyLookup *)
     protobuf_c_message_unpack (&protos__key_lookup__descriptor,
                                allocator, len, data);
}
void   protos__key_lookup__free_unpacked
                     (Protos__KeyLookup *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__key_lookup__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__registration_resp__init
                     (Protos__RegistrationResp         *message)
{
  static Protos__RegistrationResp init_value = PROTOS__REGISTRATION_RESP__INIT;
  *message = init_value;
}
size_t protos__registration_resp__get_packed_size
                     (const Protos__RegistrationResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__registration_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__registration_resp__pack
                     (const Protos__RegistrationResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__registration_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__registration_resp__pack_to_buffer
                     (const Protos__RegistrationResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__registration_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__RegistrationResp *
       protos__registration_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__RegistrationResp *)
     protobuf_c_message_unpack (&protos__registration_resp__descriptor,
                                allocator, len, data);
}
void   protos__registration_resp__free_unpacked
                     (Protos__RegistrationResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__registration_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__auth_path__user_leaf_node__init
                     (Protos__AuthPath__UserLeafNode         *message)
{
  static Protos__AuthPath__UserLeafNode init_value = PROTOS__AUTH_PATH__USER_LEAF_NODE__INIT;
  *message = init_value;
}
void   protos__auth_path__interior_node__init
                     (Protos__AuthPath__InteriorNode         *message)
{
  static Protos__AuthPath__InteriorNode init_value = PROTOS__AUTH_PATH__INTERIOR_NODE__INIT;
  *message = init_value;
}
void   protos__auth_path__root_node__init
                     (Protos__AuthPath__RootNode         *message)
{
  static Protos__AuthPath__RootNode init_value = PROTOS__AUTH_PATH__ROOT_NODE__INIT;
  *message = init_value;
}
void   protos__auth_path__init
                     (Protos__AuthPath         *message)
{
  static Protos__AuthPath init_value = PROTOS__AUTH_PATH__INIT;
  *message = init_value;
}
size_t protos__auth_path__get_packed_size
                     (const Protos__AuthPath *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__auth_path__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__auth_path__pack
                     (const Protos__AuthPath *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__auth_path__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__auth_path__pack_to_buffer
                     (const Protos__AuthPath *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__auth_path__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__AuthPath *
       protos__auth_path__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__AuthPath *)
     protobuf_c_message_unpack (&protos__auth_path__descriptor,
                                allocator, len, data);
}
void   protos__auth_path__free_unpacked
                     (Protos__AuthPath *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__auth_path__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protos__registration__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__Registration, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "publickey",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__Registration, publickey),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__registration__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = publickey */
};
static const ProtobufCIntRange protos__registration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protos__registration__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protos.Registration",
  "Registration",
  "Protos__Registration",
  "protos",
  sizeof(Protos__Registration),
  2,
  protos__registration__field_descriptors,
  protos__registration__field_indices_by_name,
  1,  protos__registration__number_ranges,
  (ProtobufCMessageInit) protos__registration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue protos__commitment_req__commitment_type__enum_values_by_number[2] =
{
  { "SELF", "PROTOS__COMMITMENT_REQ__COMMITMENT_TYPE__SELF", 0 },
  { "WITNESS", "PROTOS__COMMITMENT_REQ__COMMITMENT_TYPE__WITNESS", 1 },
};
static const ProtobufCIntRange protos__commitment_req__commitment_type__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex protos__commitment_req__commitment_type__enum_values_by_name[2] =
{
  { "SELF", 0 },
  { "WITNESS", 1 },
};
const ProtobufCEnumDescriptor protos__commitment_req__commitment_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "protos.CommitmentReq.CommitmentType",
  "CommitmentType",
  "Protos__CommitmentReq__CommitmentType",
  "protos",
  2,
  protos__commitment_req__commitment_type__enum_values_by_number,
  2,
  protos__commitment_req__commitment_type__enum_values_by_name,
  1,
  protos__commitment_req__commitment_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor protos__commitment_req__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Protos__CommitmentReq, has_type),
    PROTOBUF_C_OFFSETOF(Protos__CommitmentReq, type),
    &protos__commitment_req__commitment_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "epoch",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Protos__CommitmentReq, has_epoch),
    PROTOBUF_C_OFFSETOF(Protos__CommitmentReq, epoch),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "provider",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__CommitmentReq, provider),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__commitment_req__field_indices_by_name[] = {
  1,   /* field[1] = epoch */
  2,   /* field[2] = provider */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange protos__commitment_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protos__commitment_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protos.CommitmentReq",
  "CommitmentReq",
  "Protos__CommitmentReq",
  "protos",
  sizeof(Protos__CommitmentReq),
  3,
  protos__commitment_req__field_descriptors,
  protos__commitment_req__field_indices_by_name,
  1,  protos__commitment_req__number_ranges,
  (ProtobufCMessageInit) protos__commitment_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__key_lookup__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__KeyLookup, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "epoch",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Protos__KeyLookup, has_epoch),
    PROTOBUF_C_OFFSETOF(Protos__KeyLookup, epoch),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__key_lookup__field_indices_by_name[] = {
  1,   /* field[1] = epoch */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange protos__key_lookup__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protos__key_lookup__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protos.KeyLookup",
  "KeyLookup",
  "Protos__KeyLookup",
  "protos",
  sizeof(Protos__KeyLookup),
  2,
  protos__key_lookup__field_descriptors,
  protos__key_lookup__field_indices_by_name,
  1,  protos__key_lookup__number_ranges,
  (ProtobufCMessageInit) protos__key_lookup__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__registration_resp__field_descriptors[2] =
{
  {
    "init_epoch",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Protos__RegistrationResp, has_init_epoch),
    PROTOBUF_C_OFFSETOF(Protos__RegistrationResp, init_epoch),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "epoch_interval",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Protos__RegistrationResp, has_epoch_interval),
    PROTOBUF_C_OFFSETOF(Protos__RegistrationResp, epoch_interval),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__registration_resp__field_indices_by_name[] = {
  1,   /* field[1] = epoch_interval */
  0,   /* field[0] = init_epoch */
};
static const ProtobufCIntRange protos__registration_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protos__registration_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protos.RegistrationResp",
  "RegistrationResp",
  "Protos__RegistrationResp",
  "protos",
  sizeof(Protos__RegistrationResp),
  2,
  protos__registration_resp__field_descriptors,
  protos__registration_resp__field_indices_by_name,
  1,  protos__registration_resp__number_ranges,
  (ProtobufCMessageInit) protos__registration_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__auth_path__user_leaf_node__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__UserLeafNode, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "publickey",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__UserLeafNode, publickey),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "epoch_added",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__UserLeafNode, has_epoch_added),
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__UserLeafNode, epoch_added),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "allows_unsigned_keychange",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__UserLeafNode, has_allows_unsigned_keychange),
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__UserLeafNode, allows_unsigned_keychange),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "intlevels",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__UserLeafNode, has_intlevels),
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__UserLeafNode, intlevels),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__auth_path__user_leaf_node__field_indices_by_name[] = {
  3,   /* field[3] = allows_unsigned_keychange */
  2,   /* field[2] = epoch_added */
  4,   /* field[4] = intlevels */
  0,   /* field[0] = name */
  1,   /* field[1] = publickey */
};
static const ProtobufCIntRange protos__auth_path__user_leaf_node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor protos__auth_path__user_leaf_node__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protos.AuthPath.UserLeafNode",
  "UserLeafNode",
  "Protos__AuthPath__UserLeafNode",
  "protos",
  sizeof(Protos__AuthPath__UserLeafNode),
  5,
  protos__auth_path__user_leaf_node__field_descriptors,
  protos__auth_path__user_leaf_node__field_indices_by_name,
  1,  protos__auth_path__user_leaf_node__number_ranges,
  (ProtobufCMessageInit) protos__auth_path__user_leaf_node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__auth_path__interior_node__field_descriptors[2] =
{
  {
    "prunedchild",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__InteriorNode, has_prunedchild),
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__InteriorNode, prunedchild),
    &protos__auth_path__pruned_child__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subtree",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__InteriorNode, subtree),
    &protos__hash__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__auth_path__interior_node__field_indices_by_name[] = {
  0,   /* field[0] = prunedchild */
  1,   /* field[1] = subtree */
};
static const ProtobufCIntRange protos__auth_path__interior_node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protos__auth_path__interior_node__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protos.AuthPath.InteriorNode",
  "InteriorNode",
  "Protos__AuthPath__InteriorNode",
  "protos",
  sizeof(Protos__AuthPath__InteriorNode),
  2,
  protos__auth_path__interior_node__field_descriptors,
  protos__auth_path__interior_node__field_indices_by_name,
  1,  protos__auth_path__interior_node__number_ranges,
  (ProtobufCMessageInit) protos__auth_path__interior_node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__auth_path__root_node__field_descriptors[4] =
{
  {
    "prunedchild",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__RootNode, has_prunedchild),
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__RootNode, prunedchild),
    &protos__auth_path__pruned_child__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subtree",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__RootNode, subtree),
    &protos__hash__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prev",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__RootNode, prev),
    &protos__hash__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "epoch",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__RootNode, has_epoch),
    PROTOBUF_C_OFFSETOF(Protos__AuthPath__RootNode, epoch),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__auth_path__root_node__field_indices_by_name[] = {
  3,   /* field[3] = epoch */
  2,   /* field[2] = prev */
  0,   /* field[0] = prunedchild */
  1,   /* field[1] = subtree */
};
static const ProtobufCIntRange protos__auth_path__root_node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor protos__auth_path__root_node__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protos.AuthPath.RootNode",
  "RootNode",
  "Protos__AuthPath__RootNode",
  "protos",
  sizeof(Protos__AuthPath__RootNode),
  4,
  protos__auth_path__root_node__field_descriptors,
  protos__auth_path__root_node__field_indices_by_name,
  1,  protos__auth_path__root_node__number_ranges,
  (ProtobufCMessageInit) protos__auth_path__root_node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue protos__auth_path__pruned_child__enum_values_by_number[2] =
{
  { "LEFT", "PROTOS__AUTH_PATH__PRUNED_CHILD__LEFT", 0 },
  { "RIGHT", "PROTOS__AUTH_PATH__PRUNED_CHILD__RIGHT", 1 },
};
static const ProtobufCIntRange protos__auth_path__pruned_child__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex protos__auth_path__pruned_child__enum_values_by_name[2] =
{
  { "LEFT", 0 },
  { "RIGHT", 1 },
};
const ProtobufCEnumDescriptor protos__auth_path__pruned_child__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "protos.AuthPath.PrunedChild",
  "PrunedChild",
  "Protos__AuthPath__PrunedChild",
  "protos",
  2,
  protos__auth_path__pruned_child__enum_values_by_number,
  2,
  protos__auth_path__pruned_child__enum_values_by_name,
  1,
  protos__auth_path__pruned_child__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor protos__auth_path__field_descriptors[3] =
{
  {
    "leaf",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__AuthPath, leaf),
    &protos__auth_path__user_leaf_node__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interior",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Protos__AuthPath, n_interior),
    PROTOBUF_C_OFFSETOF(Protos__AuthPath, interior),
    &protos__auth_path__interior_node__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "root",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__AuthPath, root),
    &protos__auth_path__root_node__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__auth_path__field_indices_by_name[] = {
  1,   /* field[1] = interior */
  0,   /* field[0] = leaf */
  2,   /* field[2] = root */
};
static const ProtobufCIntRange protos__auth_path__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protos__auth_path__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protos.AuthPath",
  "AuthPath",
  "Protos__AuthPath",
  "protos",
  sizeof(Protos__AuthPath),
  3,
  protos__auth_path__field_descriptors,
  protos__auth_path__field_indices_by_name,
  1,  protos__auth_path__number_ranges,
  (ProtobufCMessageInit) protos__auth_path__init,
  NULL,NULL,NULL    /* reserved[123] */
};
