/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_c2s_2eproto__INCLUDED
#define PROTOBUF_C_c2s_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "util.pb-c.h"

typedef struct _Protos__Registration Protos__Registration;
typedef struct _Protos__CommitmentReq Protos__CommitmentReq;
typedef struct _Protos__KeyLookup Protos__KeyLookup;
typedef struct _Protos__RegistrationResp Protos__RegistrationResp;
typedef struct _Protos__AuthPath Protos__AuthPath;
typedef struct _Protos__AuthPath__UserLeafNode Protos__AuthPath__UserLeafNode;
typedef struct _Protos__AuthPath__InteriorNode Protos__AuthPath__InteriorNode;
typedef struct _Protos__AuthPath__RootNode Protos__AuthPath__RootNode;


/* --- enums --- */

typedef enum _Protos__CommitmentReq__CommitmentType {
  PROTOS__COMMITMENT_REQ__COMMITMENT_TYPE__SELF = 0,
  PROTOS__COMMITMENT_REQ__COMMITMENT_TYPE__WITNESS = 1
} Protos__CommitmentReq__CommitmentType;
typedef enum _Protos__AuthPath__PrunedChild {
  PROTOS__AUTH_PATH__PRUNED_CHILD__LEFT = 0,
  PROTOS__AUTH_PATH__PRUNED_CHILD__RIGHT = 1
} Protos__AuthPath__PrunedChild;

/* --- messages --- */

struct  _Protos__Registration
{
  ProtobufCMessage base;
  char *name;
  char *publickey;
};
#define PROTOS__REGISTRATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protos__registration__descriptor) \
    , NULL, NULL }


struct  _Protos__CommitmentReq
{
  ProtobufCMessage base;
  protobuf_c_boolean has_type;
  Protos__CommitmentReq__CommitmentType type;
  protobuf_c_boolean has_epoch;
  uint64_t epoch;
  char *provider;
};
#define PROTOS__COMMITMENT_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protos__commitment_req__descriptor) \
    , 0,0, 0,0, NULL }


struct  _Protos__KeyLookup
{
  ProtobufCMessage base;
  char *name;
  protobuf_c_boolean has_epoch;
  uint64_t epoch;
};
#define PROTOS__KEY_LOOKUP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protos__key_lookup__descriptor) \
    , NULL, 0,0 }


struct  _Protos__RegistrationResp
{
  ProtobufCMessage base;
  protobuf_c_boolean has_init_epoch;
  uint64_t init_epoch;
  protobuf_c_boolean has_epoch_interval;
  uint32_t epoch_interval;
};
#define PROTOS__REGISTRATION_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protos__registration_resp__descriptor) \
    , 0,0, 0,0 }


struct  _Protos__AuthPath__UserLeafNode
{
  ProtobufCMessage base;
  char *name;
  char *publickey;
  protobuf_c_boolean has_epoch_added;
  uint64_t epoch_added;
  protobuf_c_boolean has_allows_unsigned_keychange;
  protobuf_c_boolean allows_unsigned_keychange;
  protobuf_c_boolean has_intlevels;
  uint32_t intlevels;
};
#define PROTOS__AUTH_PATH__USER_LEAF_NODE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protos__auth_path__user_leaf_node__descriptor) \
    , NULL, NULL, 0,0, 0,0, 0,0 }


struct  _Protos__AuthPath__InteriorNode
{
  ProtobufCMessage base;
  protobuf_c_boolean has_prunedchild;
  Protos__AuthPath__PrunedChild prunedchild;
  Protos__Hash *subtree;
};
#define PROTOS__AUTH_PATH__INTERIOR_NODE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protos__auth_path__interior_node__descriptor) \
    , 0,0, NULL }


struct  _Protos__AuthPath__RootNode
{
  ProtobufCMessage base;
  protobuf_c_boolean has_prunedchild;
  Protos__AuthPath__PrunedChild prunedchild;
  Protos__Hash *subtree;
  Protos__Hash *prev;
  protobuf_c_boolean has_epoch;
  uint64_t epoch;
};
#define PROTOS__AUTH_PATH__ROOT_NODE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protos__auth_path__root_node__descriptor) \
    , 0,0, NULL, NULL, 0,0 }


struct  _Protos__AuthPath
{
  ProtobufCMessage base;
  Protos__AuthPath__UserLeafNode *leaf;
  size_t n_interior;
  Protos__AuthPath__InteriorNode **interior;
  Protos__AuthPath__RootNode *root;
};
#define PROTOS__AUTH_PATH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protos__auth_path__descriptor) \
    , NULL, 0,NULL, NULL }


/* Protos__Registration methods */
void   protos__registration__init
                     (Protos__Registration         *message);
size_t protos__registration__get_packed_size
                     (const Protos__Registration   *message);
size_t protos__registration__pack
                     (const Protos__Registration   *message,
                      uint8_t             *out);
size_t protos__registration__pack_to_buffer
                     (const Protos__Registration   *message,
                      ProtobufCBuffer     *buffer);
Protos__Registration *
       protos__registration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protos__registration__free_unpacked
                     (Protos__Registration *message,
                      ProtobufCAllocator *allocator);
/* Protos__CommitmentReq methods */
void   protos__commitment_req__init
                     (Protos__CommitmentReq         *message);
size_t protos__commitment_req__get_packed_size
                     (const Protos__CommitmentReq   *message);
size_t protos__commitment_req__pack
                     (const Protos__CommitmentReq   *message,
                      uint8_t             *out);
size_t protos__commitment_req__pack_to_buffer
                     (const Protos__CommitmentReq   *message,
                      ProtobufCBuffer     *buffer);
Protos__CommitmentReq *
       protos__commitment_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protos__commitment_req__free_unpacked
                     (Protos__CommitmentReq *message,
                      ProtobufCAllocator *allocator);
/* Protos__KeyLookup methods */
void   protos__key_lookup__init
                     (Protos__KeyLookup         *message);
size_t protos__key_lookup__get_packed_size
                     (const Protos__KeyLookup   *message);
size_t protos__key_lookup__pack
                     (const Protos__KeyLookup   *message,
                      uint8_t             *out);
size_t protos__key_lookup__pack_to_buffer
                     (const Protos__KeyLookup   *message,
                      ProtobufCBuffer     *buffer);
Protos__KeyLookup *
       protos__key_lookup__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protos__key_lookup__free_unpacked
                     (Protos__KeyLookup *message,
                      ProtobufCAllocator *allocator);
/* Protos__RegistrationResp methods */
void   protos__registration_resp__init
                     (Protos__RegistrationResp         *message);
size_t protos__registration_resp__get_packed_size
                     (const Protos__RegistrationResp   *message);
size_t protos__registration_resp__pack
                     (const Protos__RegistrationResp   *message,
                      uint8_t             *out);
size_t protos__registration_resp__pack_to_buffer
                     (const Protos__RegistrationResp   *message,
                      ProtobufCBuffer     *buffer);
Protos__RegistrationResp *
       protos__registration_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protos__registration_resp__free_unpacked
                     (Protos__RegistrationResp *message,
                      ProtobufCAllocator *allocator);
/* Protos__AuthPath__UserLeafNode methods */
void   protos__auth_path__user_leaf_node__init
                     (Protos__AuthPath__UserLeafNode         *message);
/* Protos__AuthPath__InteriorNode methods */
void   protos__auth_path__interior_node__init
                     (Protos__AuthPath__InteriorNode         *message);
/* Protos__AuthPath__RootNode methods */
void   protos__auth_path__root_node__init
                     (Protos__AuthPath__RootNode         *message);
/* Protos__AuthPath methods */
void   protos__auth_path__init
                     (Protos__AuthPath         *message);
size_t protos__auth_path__get_packed_size
                     (const Protos__AuthPath   *message);
size_t protos__auth_path__pack
                     (const Protos__AuthPath   *message,
                      uint8_t             *out);
size_t protos__auth_path__pack_to_buffer
                     (const Protos__AuthPath   *message,
                      ProtobufCBuffer     *buffer);
Protos__AuthPath *
       protos__auth_path__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protos__auth_path__free_unpacked
                     (Protos__AuthPath *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Protos__Registration_Closure)
                 (const Protos__Registration *message,
                  void *closure_data);
typedef void (*Protos__CommitmentReq_Closure)
                 (const Protos__CommitmentReq *message,
                  void *closure_data);
typedef void (*Protos__KeyLookup_Closure)
                 (const Protos__KeyLookup *message,
                  void *closure_data);
typedef void (*Protos__RegistrationResp_Closure)
                 (const Protos__RegistrationResp *message,
                  void *closure_data);
typedef void (*Protos__AuthPath__UserLeafNode_Closure)
                 (const Protos__AuthPath__UserLeafNode *message,
                  void *closure_data);
typedef void (*Protos__AuthPath__InteriorNode_Closure)
                 (const Protos__AuthPath__InteriorNode *message,
                  void *closure_data);
typedef void (*Protos__AuthPath__RootNode_Closure)
                 (const Protos__AuthPath__RootNode *message,
                  void *closure_data);
typedef void (*Protos__AuthPath_Closure)
                 (const Protos__AuthPath *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protos__registration__descriptor;
extern const ProtobufCMessageDescriptor protos__commitment_req__descriptor;
extern const ProtobufCEnumDescriptor    protos__commitment_req__commitment_type__descriptor;
extern const ProtobufCMessageDescriptor protos__key_lookup__descriptor;
extern const ProtobufCMessageDescriptor protos__registration_resp__descriptor;
extern const ProtobufCMessageDescriptor protos__auth_path__descriptor;
extern const ProtobufCMessageDescriptor protos__auth_path__user_leaf_node__descriptor;
extern const ProtobufCMessageDescriptor protos__auth_path__interior_node__descriptor;
extern const ProtobufCMessageDescriptor protos__auth_path__root_node__descriptor;
extern const ProtobufCEnumDescriptor    protos__auth_path__pruned_child__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_c2s_2eproto__INCLUDED */
