/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_util_2eproto__INCLUDED
#define PROTOBUF_C_util_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Protos__Hash Protos__Hash;
typedef struct _Protos__Commitment Protos__Commitment;
typedef struct _Protos__ServerResp Protos__ServerResp;
typedef struct _Protos__CompleteRootNode Protos__CompleteRootNode;
typedef struct _Protos__WitnessedCommitment Protos__WitnessedCommitment;


/* --- enums --- */

typedef enum _Protos__ServerResp__Message {
  PROTOS__SERVER_RESP__MESSAGE__SUCCESS = 0,
  PROTOS__SERVER_RESP__MESSAGE__NAME_EXISTS_ERR = 1,
  PROTOS__SERVER_RESP__MESSAGE__MALFORMED_ERR = 2,
  PROTOS__SERVER_RESP__MESSAGE__SERVER_ERR = 3,
  PROTOS__SERVER_RESP__MESSAGE__NAME_NOT_FOUND_ERR = 4
} Protos__ServerResp__Message;

/* --- messages --- */

struct  _Protos__Hash
{
  ProtobufCMessage base;
  protobuf_c_boolean has_len;
  int32_t len;
  size_t n_hash;
  uint32_t *hash;
};
#define PROTOS__HASH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protos__hash__descriptor) \
    , 0,0, 0,NULL }


struct  _Protos__Commitment
{
  ProtobufCMessage base;
  protobuf_c_boolean has_epoch;
  uint64_t epoch;
  Protos__Hash *root_hash;
  size_t n_signature;
  uint32_t *signature;
};
#define PROTOS__COMMITMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protos__commitment__descriptor) \
    , 0,0, NULL, 0,NULL }


struct  _Protos__ServerResp
{
  ProtobufCMessage base;
  protobuf_c_boolean has_message;
  Protos__ServerResp__Message message;
};
#define PROTOS__SERVER_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protos__server_resp__descriptor) \
    , 0,0 }


struct  _Protos__CompleteRootNode
{
  ProtobufCMessage base;
  Protos__Hash *left;
  Protos__Hash *right;
  Protos__Hash *prev;
  protobuf_c_boolean has_epoch;
  uint64_t epoch;
};
#define PROTOS__COMPLETE_ROOT_NODE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protos__complete_root_node__descriptor) \
    , NULL, NULL, NULL, 0,0 }


struct  _Protos__WitnessedCommitment
{
  ProtobufCMessage base;
  char *provider;
  Protos__Commitment *comm;
  Protos__CompleteRootNode *root;
};
#define PROTOS__WITNESSED_COMMITMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protos__witnessed_commitment__descriptor) \
    , NULL, NULL, NULL }


/* Protos__Hash methods */
void   protos__hash__init
                     (Protos__Hash         *message);
size_t protos__hash__get_packed_size
                     (const Protos__Hash   *message);
size_t protos__hash__pack
                     (const Protos__Hash   *message,
                      uint8_t             *out);
size_t protos__hash__pack_to_buffer
                     (const Protos__Hash   *message,
                      ProtobufCBuffer     *buffer);
Protos__Hash *
       protos__hash__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protos__hash__free_unpacked
                     (Protos__Hash *message,
                      ProtobufCAllocator *allocator);
/* Protos__Commitment methods */
void   protos__commitment__init
                     (Protos__Commitment         *message);
size_t protos__commitment__get_packed_size
                     (const Protos__Commitment   *message);
size_t protos__commitment__pack
                     (const Protos__Commitment   *message,
                      uint8_t             *out);
size_t protos__commitment__pack_to_buffer
                     (const Protos__Commitment   *message,
                      ProtobufCBuffer     *buffer);
Protos__Commitment *
       protos__commitment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protos__commitment__free_unpacked
                     (Protos__Commitment *message,
                      ProtobufCAllocator *allocator);
/* Protos__ServerResp methods */
void   protos__server_resp__init
                     (Protos__ServerResp         *message);
size_t protos__server_resp__get_packed_size
                     (const Protos__ServerResp   *message);
size_t protos__server_resp__pack
                     (const Protos__ServerResp   *message,
                      uint8_t             *out);
size_t protos__server_resp__pack_to_buffer
                     (const Protos__ServerResp   *message,
                      ProtobufCBuffer     *buffer);
Protos__ServerResp *
       protos__server_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protos__server_resp__free_unpacked
                     (Protos__ServerResp *message,
                      ProtobufCAllocator *allocator);
/* Protos__CompleteRootNode methods */
void   protos__complete_root_node__init
                     (Protos__CompleteRootNode         *message);
size_t protos__complete_root_node__get_packed_size
                     (const Protos__CompleteRootNode   *message);
size_t protos__complete_root_node__pack
                     (const Protos__CompleteRootNode   *message,
                      uint8_t             *out);
size_t protos__complete_root_node__pack_to_buffer
                     (const Protos__CompleteRootNode   *message,
                      ProtobufCBuffer     *buffer);
Protos__CompleteRootNode *
       protos__complete_root_node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protos__complete_root_node__free_unpacked
                     (Protos__CompleteRootNode *message,
                      ProtobufCAllocator *allocator);
/* Protos__WitnessedCommitment methods */
void   protos__witnessed_commitment__init
                     (Protos__WitnessedCommitment         *message);
size_t protos__witnessed_commitment__get_packed_size
                     (const Protos__WitnessedCommitment   *message);
size_t protos__witnessed_commitment__pack
                     (const Protos__WitnessedCommitment   *message,
                      uint8_t             *out);
size_t protos__witnessed_commitment__pack_to_buffer
                     (const Protos__WitnessedCommitment   *message,
                      ProtobufCBuffer     *buffer);
Protos__WitnessedCommitment *
       protos__witnessed_commitment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protos__witnessed_commitment__free_unpacked
                     (Protos__WitnessedCommitment *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Protos__Hash_Closure)
                 (const Protos__Hash *message,
                  void *closure_data);
typedef void (*Protos__Commitment_Closure)
                 (const Protos__Commitment *message,
                  void *closure_data);
typedef void (*Protos__ServerResp_Closure)
                 (const Protos__ServerResp *message,
                  void *closure_data);
typedef void (*Protos__CompleteRootNode_Closure)
                 (const Protos__CompleteRootNode *message,
                  void *closure_data);
typedef void (*Protos__WitnessedCommitment_Closure)
                 (const Protos__WitnessedCommitment *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protos__hash__descriptor;
extern const ProtobufCMessageDescriptor protos__commitment__descriptor;
extern const ProtobufCMessageDescriptor protos__server_resp__descriptor;
extern const ProtobufCEnumDescriptor    protos__server_resp__message__descriptor;
extern const ProtobufCMessageDescriptor protos__complete_root_node__descriptor;
extern const ProtobufCMessageDescriptor protos__witnessed_commitment__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_util_2eproto__INCLUDED */
