/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "util.pb-c.h"
void   protos__hash__init
                     (Protos__Hash         *message)
{
  static Protos__Hash init_value = PROTOS__HASH__INIT;
  *message = init_value;
}
size_t protos__hash__get_packed_size
                     (const Protos__Hash *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__hash__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__hash__pack
                     (const Protos__Hash *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__hash__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__hash__pack_to_buffer
                     (const Protos__Hash *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__hash__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__Hash *
       protos__hash__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__Hash *)
     protobuf_c_message_unpack (&protos__hash__descriptor,
                                allocator, len, data);
}
void   protos__hash__free_unpacked
                     (Protos__Hash *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__hash__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__commitment__init
                     (Protos__Commitment         *message)
{
  static Protos__Commitment init_value = PROTOS__COMMITMENT__INIT;
  *message = init_value;
}
size_t protos__commitment__get_packed_size
                     (const Protos__Commitment *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__commitment__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__commitment__pack
                     (const Protos__Commitment *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__commitment__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__commitment__pack_to_buffer
                     (const Protos__Commitment *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__commitment__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__Commitment *
       protos__commitment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__Commitment *)
     protobuf_c_message_unpack (&protos__commitment__descriptor,
                                allocator, len, data);
}
void   protos__commitment__free_unpacked
                     (Protos__Commitment *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__commitment__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__server_resp__init
                     (Protos__ServerResp         *message)
{
  static Protos__ServerResp init_value = PROTOS__SERVER_RESP__INIT;
  *message = init_value;
}
size_t protos__server_resp__get_packed_size
                     (const Protos__ServerResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__server_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__server_resp__pack
                     (const Protos__ServerResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__server_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__server_resp__pack_to_buffer
                     (const Protos__ServerResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__server_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__ServerResp *
       protos__server_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__ServerResp *)
     protobuf_c_message_unpack (&protos__server_resp__descriptor,
                                allocator, len, data);
}
void   protos__server_resp__free_unpacked
                     (Protos__ServerResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__server_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__complete_root_node__init
                     (Protos__CompleteRootNode         *message)
{
  static Protos__CompleteRootNode init_value = PROTOS__COMPLETE_ROOT_NODE__INIT;
  *message = init_value;
}
size_t protos__complete_root_node__get_packed_size
                     (const Protos__CompleteRootNode *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__complete_root_node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__complete_root_node__pack
                     (const Protos__CompleteRootNode *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__complete_root_node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__complete_root_node__pack_to_buffer
                     (const Protos__CompleteRootNode *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__complete_root_node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__CompleteRootNode *
       protos__complete_root_node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__CompleteRootNode *)
     protobuf_c_message_unpack (&protos__complete_root_node__descriptor,
                                allocator, len, data);
}
void   protos__complete_root_node__free_unpacked
                     (Protos__CompleteRootNode *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__complete_root_node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__witnessed_commitment__init
                     (Protos__WitnessedCommitment         *message)
{
  static Protos__WitnessedCommitment init_value = PROTOS__WITNESSED_COMMITMENT__INIT;
  *message = init_value;
}
size_t protos__witnessed_commitment__get_packed_size
                     (const Protos__WitnessedCommitment *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__witnessed_commitment__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__witnessed_commitment__pack
                     (const Protos__WitnessedCommitment *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__witnessed_commitment__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__witnessed_commitment__pack_to_buffer
                     (const Protos__WitnessedCommitment *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__witnessed_commitment__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__WitnessedCommitment *
       protos__witnessed_commitment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__WitnessedCommitment *)
     protobuf_c_message_unpack (&protos__witnessed_commitment__descriptor,
                                allocator, len, data);
}
void   protos__witnessed_commitment__free_unpacked
                     (Protos__WitnessedCommitment *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protos__witnessed_commitment__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protos__hash__field_descriptors[2] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Protos__Hash, has_len),
    PROTOBUF_C_OFFSETOF(Protos__Hash, len),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FIXED32,
    PROTOBUF_C_OFFSETOF(Protos__Hash, n_hash),
    PROTOBUF_C_OFFSETOF(Protos__Hash, hash),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__hash__field_indices_by_name[] = {
  1,   /* field[1] = hash */
  0,   /* field[0] = len */
};
static const ProtobufCIntRange protos__hash__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protos__hash__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protos.Hash",
  "Hash",
  "Protos__Hash",
  "protos",
  sizeof(Protos__Hash),
  2,
  protos__hash__field_descriptors,
  protos__hash__field_indices_by_name,
  1,  protos__hash__number_ranges,
  (ProtobufCMessageInit) protos__hash__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__commitment__field_descriptors[3] =
{
  {
    "epoch",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Protos__Commitment, has_epoch),
    PROTOBUF_C_OFFSETOF(Protos__Commitment, epoch),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "root_hash",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__Commitment, root_hash),
    &protos__hash__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FIXED32,
    PROTOBUF_C_OFFSETOF(Protos__Commitment, n_signature),
    PROTOBUF_C_OFFSETOF(Protos__Commitment, signature),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__commitment__field_indices_by_name[] = {
  0,   /* field[0] = epoch */
  1,   /* field[1] = root_hash */
  2,   /* field[2] = signature */
};
static const ProtobufCIntRange protos__commitment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protos__commitment__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protos.Commitment",
  "Commitment",
  "Protos__Commitment",
  "protos",
  sizeof(Protos__Commitment),
  3,
  protos__commitment__field_descriptors,
  protos__commitment__field_indices_by_name,
  1,  protos__commitment__number_ranges,
  (ProtobufCMessageInit) protos__commitment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue protos__server_resp__message__enum_values_by_number[5] =
{
  { "SUCCESS", "PROTOS__SERVER_RESP__MESSAGE__SUCCESS", 0 },
  { "NAME_EXISTS_ERR", "PROTOS__SERVER_RESP__MESSAGE__NAME_EXISTS_ERR", 1 },
  { "MALFORMED_ERR", "PROTOS__SERVER_RESP__MESSAGE__MALFORMED_ERR", 2 },
  { "SERVER_ERR", "PROTOS__SERVER_RESP__MESSAGE__SERVER_ERR", 3 },
  { "NAME_NOT_FOUND_ERR", "PROTOS__SERVER_RESP__MESSAGE__NAME_NOT_FOUND_ERR", 4 },
};
static const ProtobufCIntRange protos__server_resp__message__value_ranges[] = {
{0, 0},{0, 5}
};
const ProtobufCEnumValueIndex protos__server_resp__message__enum_values_by_name[5] =
{
  { "MALFORMED_ERR", 2 },
  { "NAME_EXISTS_ERR", 1 },
  { "NAME_NOT_FOUND_ERR", 4 },
  { "SERVER_ERR", 3 },
  { "SUCCESS", 0 },
};
const ProtobufCEnumDescriptor protos__server_resp__message__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "protos.ServerResp.Message",
  "Message",
  "Protos__ServerResp__Message",
  "protos",
  5,
  protos__server_resp__message__enum_values_by_number,
  5,
  protos__server_resp__message__enum_values_by_name,
  1,
  protos__server_resp__message__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor protos__server_resp__field_descriptors[1] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Protos__ServerResp, has_message),
    PROTOBUF_C_OFFSETOF(Protos__ServerResp, message),
    &protos__server_resp__message__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__server_resp__field_indices_by_name[] = {
  0,   /* field[0] = message */
};
static const ProtobufCIntRange protos__server_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protos__server_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protos.ServerResp",
  "ServerResp",
  "Protos__ServerResp",
  "protos",
  sizeof(Protos__ServerResp),
  1,
  protos__server_resp__field_descriptors,
  protos__server_resp__field_indices_by_name,
  1,  protos__server_resp__number_ranges,
  (ProtobufCMessageInit) protos__server_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__complete_root_node__field_descriptors[4] =
{
  {
    "left",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__CompleteRootNode, left),
    &protos__hash__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__CompleteRootNode, right),
    &protos__hash__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prev",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__CompleteRootNode, prev),
    &protos__hash__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "epoch",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Protos__CompleteRootNode, has_epoch),
    PROTOBUF_C_OFFSETOF(Protos__CompleteRootNode, epoch),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__complete_root_node__field_indices_by_name[] = {
  3,   /* field[3] = epoch */
  0,   /* field[0] = left */
  2,   /* field[2] = prev */
  1,   /* field[1] = right */
};
static const ProtobufCIntRange protos__complete_root_node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor protos__complete_root_node__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protos.CompleteRootNode",
  "CompleteRootNode",
  "Protos__CompleteRootNode",
  "protos",
  sizeof(Protos__CompleteRootNode),
  4,
  protos__complete_root_node__field_descriptors,
  protos__complete_root_node__field_indices_by_name,
  1,  protos__complete_root_node__number_ranges,
  (ProtobufCMessageInit) protos__complete_root_node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__witnessed_commitment__field_descriptors[3] =
{
  {
    "provider",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__WitnessedCommitment, provider),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comm",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__WitnessedCommitment, comm),
    &protos__commitment__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "root",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protos__WitnessedCommitment, root),
    &protos__complete_root_node__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__witnessed_commitment__field_indices_by_name[] = {
  1,   /* field[1] = comm */
  0,   /* field[0] = provider */
  2,   /* field[2] = root */
};
static const ProtobufCIntRange protos__witnessed_commitment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protos__witnessed_commitment__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protos.WitnessedCommitment",
  "WitnessedCommitment",
  "Protos__WitnessedCommitment",
  "protos",
  sizeof(Protos__WitnessedCommitment),
  3,
  protos__witnessed_commitment__field_descriptors,
  protos__witnessed_commitment__field_indices_by_name,
  1,  protos__witnessed_commitment__number_ranges,
  (ProtobufCMessageInit) protos__witnessed_commitment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
